# Generated by Django 3.0.1 on 2020-02-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_reserved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_under_nego',
            field=models.BooleanField(null=True),
        ),
    ]
