# Generated by Django 3.0.1 on 2020-01-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
